### ISSUE TITLE
Error importing JSON with bigip_waf_policy: cannot unmarshal number into Go struct field

### ISSUE THREAD

**Issue by spiedra** [F5Networks/terraform-provider-bigip#900] opened 2023-11-08 02:37 UTC
### Environment

 * TMOS/Bigip Version: 17.1.0
 * Terraform Version: 1.6.3
 * Terraform bigip provider Version: 1.20.0

### Summary

I am encountering an issue when attempting to import a JSON file for a security policy. I'm using the `bigip_waf_policy` resource to import a JSON-formatted security policy. However, when running `terraform apply`, I receive an error.

### Steps To Reproduce

1. Define the bigip_waf_policy resource and all the required configuration in Terraform.
```
resource "bigip_waf_policy" "this" {
    application_language = "utf-8"
    name                 = "Test-asm-policy"
    partition            = "Common"
    template_name        = "POLICY_TEMPLATE_FUNDAMENTAL"
    type                 = "security"
    policy_import_json   = file("${path.module}/Test-asm-policy.json")
}
```
3. Place the JSON policy file in the project directory.
4. Run `terraform init` 
5. Run `terraform apply -out Test-asm-policy`
6. Run `terraform apply "Test-asm-policy"`

Error Output:
```
bigip_waf_policy.this: Creating...

Error: Error in Importing AWAF json (Test-asm-policy): json: cannot unmarshal number 16974042752222049 into Go struct field Upload.lastUpdateMicros of type int
```
### Expected Behavior
The JSON file should be imported successfully without errors.

### Actual Behavior
The import process fails, producing the above error message. **It's worth noting that the field lastUpdateMicros mentioned in the error does not exist in my JSON file**.

Any guidance or assistance in resolving this error would be greatly appreciated.

**Comment by RavinderReddyF5** [comment] 2023-11-08 05:49
Hi @spiedra Is it possible to share the AWAF json trying to import?

**Comment by spiedra** [comment] 2023-11-09 18:34
Sure, I'm trying to upload the same security policy as this example:

https://github.com/f5devcentral/awaf-terraform/blob/main/0.Appendix/Common_scenario5__2022-8-12_15-35-45__prod1.f5demo.com.json

Now, I've changed the following keys in the JSON: 

- name
- description
- softwareVersion

**Comment by spiedra** [comment] 2023-11-24 19:56
Hi @RavinderReddyF5, were you able to check this? Now, I'm getting the same issue when creating a security policy, but I'm not sure why this is happening.

**Comment by pgouband** [comment] 2023-12-14 11:11
Hi,

Thanks for reporting. Added to the backlog and internal tracking ID for this request is: INFRAANO-1400.

**Comment by RavinderReddyF5** [comment] 2023-12-15 04:53
Hi @spiedra,

```
➜  terraform-provider-bigip git:(master) terraform version
Terraform v1.5.0
on darwin_arm64
+ provider registry.terraform.io/f5networks/bigip v1.20.1
````

I have not able to reproduce this issue please try on v1.20.1(BIG-IP)

```
 # bigip_waf_policy.test_basic_pol_iso will be created
  + resource "bigip_waf_policy" "test_basic_pol_iso" {
      + application_language = "utf-8"
      + case_insensitive     = false
      + description          = (known after apply)
      + enable_passivemode   = false
      + id                   = (known after apply)
      + name                 = "Test-asm-policy"
      + partition            = "Common"
      + policy_export_json   = (known after apply)
      + policy_id            = (known after apply)
      + policy_import_json   = jsonencode(
            {
              + policy = {
                  + applicationLanguage = "utf-8"
                  + caseInsensitive     = false
                  + description         = "Fundamental Policy"
                  + enablePassiveMode   = false
                  + enforcementMode     = "blocking"
                  + fullPath            = "/Common/scenario5"
                  + general             = {
                      + enforcementReadinessPeriod = 0
                    }
                  + name                = "scenario5"
                  + policy-builder      = {
                      + enableUntrustedTrafficSiteChangeTracking = true
                      + learningMode                             = "manual"
                      + trafficTighten                           = {
                          + maxModificationSuggestionScore = 60
                          + totalRequests                  = 10000
                        }
                      + untrustedTrafficLoosen                   = {
                          + differentSources       = 10
                          + minHoursBetweenSamples = 0.5
                        }
                      + untrustedTrafficSiteChangeTracking       = {
                          + differentSources         = 5
                          + minMinutesBetweenSamples = 15
                        }
                    }
                  + protocolIndependent = false
                  + softwareVersion     = "16.1.2"
                  + template            = {
                      + name = "POLICY_TEMPLATE_FUNDAMENTAL"
                    }
                  + type                = "security"
                }
            }
        )
      + template_name        = "POLICY_TEMPLATE_FUNDAMENTAL"
      + type                 = "security"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

bigip_waf_policy.test_basic_pol_iso: Creating...
bigip_waf_policy.test_basic_pol_iso: Still creating... [10s elapsed]



bigip_waf_policy.test_basic_pol_iso: Still creating... [20s elapsed]
bigip_waf_policy.test_basic_pol_iso: Still creating... [30s elapsed]
bigip_waf_policy.test_basic_pol_iso: Creation complete after 39s [id=J-nKFoHicbfxlE8LDeoL2w]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by pgouband** [comment] 2024-01-02 16:18
Hi,

We are closing this request now.
Please re-open if required.

**Closed as completed by pgouband** 2024-01-02 16:18 UTC
Labels: bug, Backlog, waiting-response
