### ISSUE TITLE
 resourceBigipLtmVirtualAddressRead/VirtualAddresses() failed to parse json response if RouteAdvertisement is "selective"

### ISSUE THREAD

**Issue by hoangnng** [F5Networks/terraform-provider-bigip#323] opened 2020-08-20 21:02 UTC
Issue:
Calling session.VirtualAddresses() with a VIP's RouteAdvertisement set to "selective" caused this error
"Unknown boolean conversion for RouteAdvertisement: selective".
This happens after upgrading big-ip to 13.0.

This issue was actually found by using the go-bigip client, https://github.com/f5devcentral/go-bigip.
However, it will occur with terraform for bigip as well as it's using the same go-bigip client. See
https://github.com/F5Networks/terraform-provider-bigip/blob/master/bigip/resource_bigip_ltm_virtual_address.go#L109

Analysis:
It appears the json declaration for virtualAddressDTO still uses the old boolean value "enabled" (true) for RouteAdvertisement
https://github.com/f5devcentral/go-bigip/blob/master/ltm.go#L596
This is a knowledge base article about the change of "enabled" to "selective" for RouteAdvertisement
https://support.f5.com/csp/article/K85543242.
Also note that RouteAdvertisement is an enum (disabled, enabled, selective, always, all, any) starting with bigip 13.0.

**Comment by nmenant** [comment] 2020-08-25 11:32
Thanks for the feedback, we will be looking into this quickly. 

we've created TER-438 internally to track this issue

**Comment by papineni87** [comment] 2020-09-15 15:07
@hoangnng  I just pushed a fix for it, can you clone the repo and let me know the issue is addressed or not ?

**Comment by papineni87** [comment] 2020-10-15 13:04
Issue fixed in 1.3.3 release

**Closed by papineni87** 2020-10-15 13:04 UTC
Labels: bug
