### ISSUE TITLE
Allow managing default profiles

### ISSUE THREAD

**Issue by DavidGamba** [F5Networks/terraform-provider-bigip#461] opened 2021-03-30 16:51 UTC
### Is your feature request related to a problem? Please describe.

The F5 allows users to modify default profiles (this is a really bad design decision but we have to live with it): 
[From the docs](https://techdocs.f5.com/kb/en-us/products/big-ip_ltm/manuals/product/ltm-concepts-11-5-1/7.html): 
>You can modify a default profile, but you cannot create or delete a default profile.

That means that there could be manually edited default profiles in our config.

From the documentation of the [`bigip_ltm_profile_http` resource](https://registry.terraform.io/providers/F5Networks/bigip/latest/docs/resources/bigip_ltm_profile_http) it says that `defaults_from` is required, meaning there is no way to create a custom profile that doesn't inherit from a parent profile.
Additionally, it means that you can't import a default profile and have it managed in code.

Not being able to import a default profile is a problem because as mentioned before, default profiles can be manually edited and not having them in code means there is no audit record in Terraform. Furthermore, changes made to them will be inherited to all profiles that depend on them without record.

### Describe the solution you'd like
A couple possible solutions:

- Make `defaults_from` optional in the `bigip_ltm_profile_http` resource so we can *import default profiles*.

- Make `defaults_from` optional in the `bigip_ltm_profile_http` resource so there is no need to have a parent profile and every value of a custom profile is explicit.

- Make a `bigip_ltm_profile_default_http` resource that has static values so we can have a safe static resource to inherit from.

NOTE: The resource also doesn't include all knobs available on the UI.

### Describe alternatives you've considered

With `defaults_from` being a required argument we can't try creating a custom profile with fully explicit configuration. Additionally, the resource doesn't seem to support all configuration knobs available in the F5 UI.

**Comment by nmenant** [comment] 2021-05-03 09:26
Hi,

Our apologies for not coming back earlier on this one. We did some reviews and the challenge is that the BIG-IP, by design, will always have to refer to a parent profile. 

The best path forward will be for us to let you handle #1: Make defaults_from optional in the bigip_ltm_profile_http resource so we can import default profiles.

Tracking this internally with INFRAANO-336

**Comment by RavinderReddyF5** [comment] 2021-08-05 14:02
@DavidGamba fixed in v1.11.0

**Closed as completed by RavinderReddyF5** 2021-08-05 14:02 UTC
Labels: enhancement
