### ISSUE TITLE
bigip_ltm_node fails when monitor is set and session is not defined

### ISSUE THREAD

**Issue by smerrell** [F5Networks/terraform-provider-bigip#521] opened 2021-06-24 23:35 UTC
### Environment

 * TMOS/Bigip Version: 14.1.2.2 and 14.1.4
 * Terraform Version: v0.14.11
 * Terraform bigip provider Version: 1.10.0

### Summary

When modifying a node that has a monitor set, the bigip provider will fail with the message:

```
Error: Error modifying node /Common/testnode: HTTP 400 :: {"code":400,"message":"invalid property value \"session\":\"monitor-enabled\"","errorStack":[],"apiError":26214401}
```

### Steps To Reproduce

1. Create a `bigip_ltm_node` with a monitor set:

```hcl
provider "bigip" {
  address    = "<address>"
}

resource "bigip_ltm_node" "test_node" {
  name             = "/Common/test_node"
  description      = ""
  connection_limit = "0"
  dynamic_ratio    = "1"
  monitor          = "/Common/gateway_icmp"
  rate_limit = "disabled"
  address    = "192.168.1.101"
}
```
2. Apply changes to create the node
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # bigip_ltm_node.test_node will be created
  + resource "bigip_ltm_node" "test_node" {
      + address          = "192.168.1.101"
      + connection_limit = 0
      + dynamic_ratio    = 1
      + id               = (known after apply)
      + monitor          = "/Common/gateway_icmp"
      + name             = "/Common/test_node"
      + rate_limit       = "disabled"
      + ratio            = (known after apply)
      + session          = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------
```
3. Modify the HCL in some way, like adding a description
```hcl
resource "bigip_ltm_node" "test_node" {
  name             = "/Common/test_node"
  description      = "Added a description"
  connection_limit = "0"
  dynamic_ratio    = "1"
  monitor          = "/Common/gateway_icmp"
  rate_limit = "disabled"
  address    = "192.168.1.101"
}
```
4. Apply the changes again

### Expected Behavior
The terraform apply to succeed

### Actual Behavior
The terraform apply fails with the following error:
```
Error: Error modifying node /Common/testnode: HTTP 400 :: {"code":400,"message":"invalid property value \"session\":\"monitor-enabled\"","errorStack":[],"apiError":26214401}
```

## Notes

From what I can tell, setting session directly only allows for two options: `user-enabled` and `user-disabled` from the [docs I found](https://clouddocs.f5.com/cli/tmsh-reference/latest/modules/ltm/ltm_node.html).

In the bigip_ltm_node code, it appears it pulls the session from the go-bigip client [here](https://github.com/F5Networks/terraform-provider-bigip/blob/master/bigip/resource_bigip_ltm_node.go#L226). When I pulled the session value from the go-bigip client directly, I get the value `monitor-enabled`. Which explains why modifying the resource is failing. I tried to research where `monitor-enabled` comes from but was unsuccessful.

## Possible workaround

If I explicitly set the `session` attribute, I can get the apply to work. I haven't yet been able to determine if setting session while having a monitor set would have any adverse affects, though. So I have been hesitant to use that. The only other option I have found is to downgrade the provider to 1.9.0.

**Comment by papineni87** [comment] 2021-06-25 17:04
Thanks for reporting the issue, tracking with infraano-428

**Comment by papineni87** [comment] 2021-06-28 14:06
@smerrell Fixed the issue by converting node session value as either "user-enabled " or "user-disabled"

Can you clone the latest devel branch and see the issue is fixed or not ?

**Comment by smerrell** [comment] 2021-06-28 15:32
@papineni87 Yes I'll give that a try. I also wanted to update that once I have a monitor on the node, the F5 changes the session status to `monitor-enabled`. So even when I had set the value to `user-enabled` it gets overridden. Which also means that every time I do a terraform plan/apply, session will show up as a change.

**Comment by papineni87** [comment] 2021-06-28 16:29
So here is the behaviour, whenever any monitor is attached to node ( even if it is not given, default monitor will be there ) read call from the bigip always gives node session attribute as "monitor-enabled". So even if we give session state as "user-enabled" it will take as "monitor-enabled" . ( as read call from bigip gives monitor-enabled )

 So i changed this behaviour in my fix  with the session attribute will be "user-enabled"  if the read call from bigip gives as "monitor-enabled" . I hope this should solve the issue and do let me know if you see any deviation.

**Comment by smerrell** [comment] 2021-06-28 20:32
@papineni87 thanks! I pulled down the devel branch and tested the changes. I was able to successfully create a node and then modify it.

**Comment by trinaths** [comment] 2021-07-06 17:29
@smerrell - Closing this issue. Thank you.

**Closed as completed by trinaths** 2021-07-06 17:29 UTC
Labels: bug
